title: My Tech Blog
description: All IT knowledge at one place!
theme: just-the-docs

url: https://dev-ops-aws.github.io/aws-docs

aux_links:
  Template Repository: https://github.com/dev-ops-aws/aws-docs
